/**
 * webgl-profiles-captured.ts — AUTO-GENERATED by
 *   pnpm --filter @mosaiq/sdk run bench:integrate-profiles
 *
 * DO NOT EDIT BY HAND. Drop a new `*.json` capture into
 * `packages/sdk/bench/captured-profiles/` and re-run integrate;
 * commit the regenerated TS together with the JSON.
 *
 * CI runs `bench:integrate-profiles -- --check` to detect drift
 * between the on-disk JSONs and this file.
 */

import type { WebglProfile } from './webgl-profiles.js';

// (no captured profiles yet — see bench/captured-profiles/README.md)

export const KNOWN_PROFILES_CAPTURED: readonly WebglProfile[] = [];
