/**
 * Per-OS 字体白名单。
 * 指纹探测常通过「偏僻字体是否存在」判断 OS；返回的列表必须与 OS family 自洽。
 *
 * 数据来源：Windows 11 / macOS Sonoma / Ubuntu 24.04 默认安装。
 * 略去极偏僻字体以减小列表波动。
 */

export const WIN11_FONTS: readonly string[] = [
  'Arial',
  'Arial Black',
  'Bahnschrift',
  'Calibri',
  'Cambria',
  'Cambria Math',
  'Candara',
  'Comic Sans MS',
  'Consolas',
  'Constantia',
  'Corbel',
  'Courier New',
  'Ebrima',
  'Franklin Gothic Medium',
  'Gabriola',
  'Gadugi',
  'Georgia',
  'HoloLens MDL2 Assets',
  'Impact',
  'Ink Free',
  'Javanese Text',
  'Leelawadee UI',
  'Lucida Console',
  'Lucida Sans Unicode',
  'Malgun Gothic',
  'Marlett',
  'Microsoft Himalaya',
  'Microsoft JhengHei',
  'Microsoft New Tai Lue',
  'Microsoft PhagsPa',
  'Microsoft Sans Serif',
  'Microsoft Tai Le',
  'Microsoft YaHei',
  'Microsoft Yi Baiti',
  'MingLiU-ExtB',
  'Mongolian Baiti',
  'MS Gothic',
  'MV Boli',
  'Myanmar Text',
  'Nirmala UI',
  'Palatino Linotype',
  'Segoe MDL2 Assets',
  'Segoe Print',
  'Segoe Script',
  'Segoe UI',
  'Segoe UI Emoji',
  'Segoe UI Historic',
  'Segoe UI Symbol',
  'SimSun',
  'Sitka',
  'Sylfaen',
  'Symbol',
  'Tahoma',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
  'Webdings',
  'Wingdings',
  'Yu Gothic',
];

export const WIN10_FONTS: readonly string[] = WIN11_FONTS.filter(
  (f) => f !== 'Bahnschrift' && f !== 'HoloLens MDL2 Assets' && f !== 'Ink Free',
);

export const MACOS_SONOMA_FONTS: readonly string[] = [
  'American Typewriter',
  'Andale Mono',
  'Apple Braille',
  'Apple Chancery',
  'Apple Color Emoji',
  'Apple SD Gothic Neo',
  'Apple Symbols',
  'AppleGothic',
  'AppleMyungjo',
  'Arial',
  'Arial Black',
  'Arial Hebrew',
  'Arial Narrow',
  'Arial Rounded MT Bold',
  'Arial Unicode MS',
  'Avenir',
  'Avenir Next',
  'Avenir Next Condensed',
  'Baskerville',
  'Big Caslon',
  'Bodoni 72',
  'Brush Script MT',
  'Chalkboard',
  'Chalkduster',
  'Charter',
  'Cochin',
  'Comic Sans MS',
  'Copperplate',
  'Courier',
  'Courier New',
  'DIN Alternate',
  'Didot',
  'Futura',
  'Geneva',
  'Georgia',
  'Gill Sans',
  'Helvetica',
  'Helvetica Neue',
  'Hiragino Kaku Gothic Pro',
  'Hiragino Mincho Pro',
  'Hoefler Text',
  'Impact',
  'Iowan Old Style',
  'Kefa',
  'Lucida Grande',
  'Marker Felt',
  'Menlo',
  'Microsoft Sans Serif',
  'Monaco',
  'Noteworthy',
  'Optima',
  'Palatino',
  'Papyrus',
  'PingFang HK',
  'PingFang SC',
  'PingFang TC',
  'Plantagenet Cherokee',
  'San Francisco',
  'Savoye LET',
  'Seravek',
  'SignPainter',
  'Skia',
  'Snell Roundhand',
  'Songti SC',
  'Songti TC',
  'Symbol',
  'Tahoma',
  'Times',
  'Times New Roman',
  'Trattatello',
  'Trebuchet MS',
  'Verdana',
  'Webdings',
  'Wingdings',
  'Zapf Dingbats',
  'Zapfino',
];

/**
 * Ubuntu 22.04 LTS 默认字体集（fonts-ubuntu / fonts-dejavu / fonts-liberation /
 * fonts-noto-core / fonts-freefont-ttf / fonts-tlwg / fonts-thai-tlwg / fonts-urw）。
 *
 * 来源：Ubuntu desktop 标准安装后 `fc-list :family` 输出去重得到 family 名。
 * 略去过于偏门的拉丁/泰语/印度语字族以减小列表波动；保留主流通用 + Ubuntu 自带签名字体。
 *
 * 注意：Ubuntu Server 默认字体很少（< 20），这个列表对应的是 Ubuntu Desktop。
 */
export const UBUNTU_2204_FONTS: readonly string[] = [
  'Bitstream Charter',
  'C059',
  'D050000L',
  'DejaVu Math TeX Gyre',
  'DejaVu Sans',
  'DejaVu Sans Mono',
  'DejaVu Serif',
  'Droid Sans Fallback',
  'FreeMono',
  'FreeSans',
  'FreeSerif',
  'KacstArt',
  'KacstBook',
  'KacstDecorative',
  'KacstDigital',
  'KacstFarsi',
  'KacstLetter',
  'KacstNaskh',
  'KacstOffice',
  'KacstOne',
  'KacstPen',
  'KacstPoster',
  'KacstQurn',
  'KacstScreen',
  'KacstTitle',
  'KacstTitleL',
  'Khmer OS',
  'Khmer OS System',
  'Liberation Mono',
  'Liberation Sans',
  'Liberation Sans Narrow',
  'Liberation Serif',
  'Lohit Bengali',
  'Lohit Devanagari',
  'Lohit Gujarati',
  'Lohit Punjabi',
  'Lohit Tamil',
  'Loma',
  'Mukti Narrow',
  'Nimbus Mono PS',
  'Nimbus Roman',
  'Nimbus Sans',
  'Nimbus Sans Narrow',
  'Noto Color Emoji',
  'Noto Mono',
  'Noto Sans',
  'Noto Sans Mono',
  'Noto Serif',
  'OpenSymbol',
  'P052',
  'Padauk',
  'Phetsarath OT',
  'Sawasdee',
  'Standard Symbols PS',
  'Tibetan Machine Uni',
  'Tlwg Mono',
  'Tlwg Typewriter',
  'Tlwg Typist',
  'Tlwg Typo',
  'URW Bookman',
  'URW Gothic',
  'Ubuntu',
  'Ubuntu Condensed',
  'Ubuntu Mono',
  'Umpush',
  'Waree',
  'Z003',
];
